apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v0.9.16/external-secrets.yaml

patches:
  - path: service-account-patch.yaml
    target:
      kind: ServiceAccount
      name: external-secrets