apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets


apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webserver-db-credentials
  namespace: webserver
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: webserver-db-credentials   
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: boba-tech-test-dev-db-credentials   
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: boba-tech-test-dev-db-credentials
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: boba-tech-test-dev-db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: boba-tech-test-dev-db-credentials
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: boba-tech-test-dev-db-credentials
        property: dbname