apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webserver

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: webserver
    newName: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/devops-eks-demo-webserver
    newTag: placeholder   # CI rewrites this line on every successful build