apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webserver

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: webserver
  newName: 676206939809.dkr.ecr.eu-west-2.amazonaws.com/boba-tech-test-webserver
  newTag: 702cd65
